Repository SRP-Platform/srp_platform, pull requests merged in 2025-05, with the labels that each got.

#36 init zuul
  .github/CODEOWNERS
  .zuul.yaml
  playbooks/testjob.yaml
Labels: check, marge

#37 test 1
  .github/workflows/Check syntax.yaml
  .jobs/cpplint.yaml
  .jobs/unit_tests_platform.yaml
  .zuul.yaml
  playbooks/testjob.yaml
Labels: check, marge-bot

#39 fix3
  .jobs/cpplint.yaml
  .jobs/itf.yaml
  .zuul.yaml
  tests/BUILD
  tools/qemu/BUILD
  tools/qemu/rule/qemu_sim.bzl
  tools/qemu/wait_for_qemu.py
Labels: check, marge-bot

#35 Update README.md
  README.md
Labels: check, marge-bot

#40 test
  tools/qemu/rule/qemu_sim.bzl
Labels: check, merge-bot

#42 add tool
  third_party/python/BUILD
  third_party/python/requirements.txt
  tools/ci/BUILD
  tools/ci/is_user_allowed.py
Labels: check, merge-bot

#33 Add basic Mavlink parser
  third_party/python/BUILD
  third_party/python/requirements.txt
  tools/mavlink/BUILD
  tools/mavlink/gen_mavlink_defs.py
  tools/mavlink/mavlink_gen.bzl
Labels: enhancement, check, merge

#46 fix f-string backslash error
  .bazelrc
  tools/model_generator/platform/sm/cpp_extractor.py
Labels: bug, check, merge
